General:
  general_badge_size: 100
  general_edge_padding: 30
  general_badge_position: top-left
Background:
  background-color: "#fe019a"
  background_opacity: 60
Border:
  border-color: "#fe019a"
  border-radius: 10
  border_width: 4
Shadow:
  shadow_enable: true
  shadow_blur: 8
  shadow_offset_x: 2
  shadow_offset_y: 2