General:
  general_badge_size: 100
  general_edge_padding: 30
  general_badge_position: top-left
  general_text_padding: 12
  use_dynamic_sizing: true
Text:
  fallback_font: DejaVuSans.ttf
  font: AvenirNextLTProBold.otf
  text-color: '#FFFFFF'
  text-size: 90
Background:
  background-color: '#000000'
  background_opacity: 40
Border:
  border-color: '#000000'
  border_radius: 10
  border_width: 1
  border-radius: 10
Shadow:
  shadow_blur: 8
  shadow_enable: false
  shadow_offset_x: 2
  shadow_offset_y: 2
ImageBadges:
  codec_image_directory: images/resolution
  enable_image_badges: true
  fallback_to_text: true
  image_mapping:
    '480': 480.png
    '720': 720.png
    '1080': 1080.png
    '2160': 2160.png
    1080p: 1080p.png
    1080pdv: 1080pdv.png
    1080pdvhdr: 1080pdvhdr.png
    1080pdvhdrplus: 1080pdvhdrplus.png
    1080phdr: 1080phdr.png
    1080pplus: 1080pplus.png
    480p: 480p.png
    480pdv: 480pdv.png
    480pdvhdr: 480pdvhdr.png
    480pdvhdrplus: 480pdvhdrplus.png
    480phdr: 480phdr.png
    480pplus: 480pplus.png
    4k: 4k.png
    4kdv: 4kdv.png
    4kdvhdr: 4kdvhdr.png
    4kdvhdrplus: 4kdvhdrplus.png
    4khdr: 4khdr.png
    4kplus: 4kplus.png
    4ksvg: 4k.svg
    576p: 576p.png
    576pdv: 576pdv.png
    576pdvhdr: 576pdvhdr.png
    576pdvhdrplus: 576pdvhdrplus.png
    576phdr: 576phdr.png
    576pplus: 576pplus.png
    720p: 720p.png
    720pdv: 720pdv.png
    720pdvhdr: 720pdvhdr.png
    720pdvhdrplus: 720pdvhdrplus.png
    720phdr: 720phdr.png
    720pplus: 720pplus.png
    dv: dv.png
    dvhdr: dvhdr.png
    dvhdrplus: dvhdrplus.png
    hdr: hdr.png
    plus: plus.png
  image_padding: 20
