General:
  general_badge_size: 100
  general_edge_padding: 30
  general_badge_position: top-right
  general_text_padding: 12
  use_dynamic_sizing: true  # Set to false to use fixed badge size
Text:
  font: "AvenirNextLTProBold.otf"
  fallback_font: "DejaVuSans.ttf"
  text-color: "#000000"
  text-size: 80
Background:
  background-color: "#FF69B4"
  background_opacity: 60
Border:
  border-color: "#000000"
  border-radius: 10
  border_width: 1
Shadow:
  shadow_enable: true
  shadow_blur: 8
  shadow_offset_x: 2
  shadow_offset_y: 2

# Configuration for image-based badges
ImageBadges:
  enable_image_badges: true  # Master switch to enable/disable image badges
  codec_image_directory: "images/codec"  # Directory containing codec images
  fallback_to_text: true  # If true, use text when image not found
  image_mapping:  # Optional: Define specific mappings from codec text to image filenames
    "DTS-HD MA": "DTS-HD.png"
    "TRUEHD ATMOS": "TrueHD-Atmos.png"
    "ATMOS": "Atmos.png"
    "DOLBY DIGITAL PLUS": "DigitalPlus.png"
    "TRUEHD": "TrueHD.png"
    "DTS-X": "DTS-X.png"