General:
  general_badge_size: 100
  general_edge_padding: 30
  general_badge_position: top-left
  general_text_padding: 12
  use_dynamic_sizing: true  # Set to false to use fixed badge size
Text:
  font: "AvenirNextLTProBold.otf"
  fallback_font: "DejaVuSans.ttf"
  text-color: "#FFFFFF"
  text-size: 90
Background:
  background-color: "#FFFF00"
  background_opacity: 40
Border:
  border-color: "#FFFF00"
  border-radius: 10
  border_width: 1
Shadow:
  shadow_enable: false
  shadow_blur: 8
  shadow_offset_x: 2
  shadow_offset_y: 2

# Configuration for image-based badges
ImageBadges:
  enable_image_badges: true   # Master switch to enable/disable image badges
  codec_image_directory: "images/codec"   # Directory containing codec images
  fallback_to_text: true   # If true, use text when image not found
  image_mapping:   # Optional: Define specific mappings from codec text to image filenames
    "DTS-HD MA": "DTS-HD.png"
    "TRUEHD ATMOS": "TrueHD-Atmos.png"
    "ATMOS": "Atmos.png"
    "DOLBY DIGITAL PLUS": "DigitalPlus.png"
    "TRUEHD": "TrueHD.png"
    "DTS-X": "DTS-X.png"
    "Plus-DTS-X": "Plus-DTS-X.png"
    "Plus-TrueHD-Atmos": "Plus-TrueHD-Atmos.png"
    "Plus-TrueHD": "Plus-TrueHD.png"
    "Plus": "Plus.png"
    "DigitalPlus": "DigitalPlus.png"
    "DV-Atmos": "DV-Atmos.png"
    "DV-DigitalPlus": "DV-DigitalPlus.png"
    "DV-DTS-HD": "DV-DTS-HD.png"
    "DV-DTS-X": "DV-DTS-X.png"
    "DV-HDR_extended": "DV-HDR_extended.png"
    "DV-HDR-Atmos": "DV-HDR-Atmos.png"
    "DV-HDR-DigitalPlus": "DV-HDR-DigitalPlus.png"
    "DV-HDR-DTS-HD": "DV-HDR-DTS-HD.png"
    "DV-HDR-DTS-X": "DV-HDR-DTS-X.png"
    "DV-HDR-TrueHD-Atmos": "DV-HDR-TrueHD-Atmos.png"
    "DV-HDR-TrueHD": "DV-HDR-TrueHD.png"
    "DV-HDR": "DV-HDR.png"
    "DV-Plus_extended": "DV-Plus_extended.png"
    "DV-Plus-Atmos": "DV-Plus-Atmos.png"
    "DV-Plus-DigitalPlus": "DV-Plus-DigitalPlus.png"
    "DV-Plus-DTS-HD": "DV-Plus-DTS-HD.png"
    "DV-Plus-DTS-X": "DV-Plus-DTS-X.png"
    "DV-Plus-TrueHD-Atmos": "DV-Plus-TrueHD-Atmos.png"
    "DV-Plus-TrueHD": "DV-Plus-TrueHD.png"
    "DV-Plus": "DV-Plus.png"
    "DV-TrueHD-Atmos": "DV-TrueHD-Atmos.png"
    "DV-TrueHD": "DV-TrueHD.png"
    "DV": "DV.png"
    "HDR-Atmos": "HDR-Atmos.png"
    "HDR-DigitalPlus": "HDR-DigitalPlus.png"
    "HDR-DTS-HD": "HDR-DTS-HD.png"
    "HDR-DTS-X": "HDR-DTS-X.png"
    "HDR-TrueHD-Atmos": "HDR-TrueHD-Atmos.png"
    "HDR-TrueHD": "HDR-TrueHD.png"
    "HDR": "HDR.png"
    "Plus-Atmos": "Plus-Atmos.png"
    "Plus-DigitalPlus": "Plus-DigitalPlus.png"
    "Plus-DTS-HD": "Plus-DTS-HD.png"