General:
  general_badge_position: bottom-right-flush
  general_badge_size: 120
  general_edge_padding: 0
  general_text_padding: 0
  use_dynamic_sizing: false
  enabled: true

Awards:
  color_scheme: yellow
  award_sources:
    - oscars
    - emmys
    - golden
    - bafta
    - cannes
    - berlinale
    - cesar
    - choice
    - imdb
    - letterboxd
    - metacritic
    - netflix
    - razzie
    - rotten
    - rottenverified
    - spirit
    - sundance
    - venice

Text:
  fallback_font: DejaVuSans.ttf
  font: AvenirNextLTProBold.otf
  text-color: '#FFFFFF'
  text-size: 90

Background:
  background-color: '#000000'
  background_opacity: 40

Border:
  border-color: '#000000'
  border-radius: 10
  border_width: 1

Shadow:
  shadow_blur: 8
  shadow_enable: false
  shadow_offset_x: 2
  shadow_offset_y: 2

ImageBadges:
  codec_image_directory: images/awards
  enable_image_badges: true
  fallback_to_text: false
  image_mapping:
    oscars: oscars.png
    emmys: emmys.png
    golden: golden.png
    bafta: bafta.png
    cannes: cannes.png
    berlinale: berlinale.png
    cesar: cesar.png
    choice: choice.png
    imdb: imdb.png
    letterboxd: letterboxd.png
    metacritic: metacritic.png
    netflix: netflix.png
    razzie: razzie.png
    rotten: rotten.png
    rottenverified: rottenverified.png
    spirit: spirit.png
    sundance: sundance.png
    venice: venice.png
  image_padding: 0
