General:
  general_badge_size: 100
  general_edge_padding: 30
  general_badge_position: top-right
  general_text_padding: 12
  use_dynamic_sizing: true  # Set to false to use fixed badge size
Text:
  font: "AvenirNextLTPro-Bold.ttf"
  fallback_font: "DejaVuSans.ttf"
  text-color: "#000000"
  text-size: 80
Background:
  background-color: "#FF69B4"
  background_opacity: 60
Border:
  border-color: "#000000"
  border-radius: 10
  border_width: 1
Shadow:
  shadow_enable: true
  shadow_blur: 8
  shadow_offset_x: 2
  shadow_offset_y: 2