General:
  # General badge settings
  general_badge_position: "top-left"  # Position of the badge (top-left, top-right, bottom-left, bottom-right)
  general_badge_size: 100             # Base size of the badge in pixels
  general_edge_padding: 30            # Padding from the edge of the poster in pixels
  general_text_padding: 12            # Padding around text inside the badge
  use_dynamic_sizing: true            # Automatically adjust badge size based on content

Text:
  # Text appearance settings
  fallback_font: "DejaVuSans.ttf"     # Fallback font if primary font is not available
  font: ""                            # Primary font file to use (place in fonts directory)
  text-color: "#FFFFFF"               # Text color (hex code)
  text-size: 90                       # Text size relative to badge size

Background:
  # Badge background settings
  background-color: "#000000"         # Background color (hex code)
  background_opacity: 40              # Background opacity (0-100)

Border:
  # Badge border settings
  border-color: "#000000"             # Border color (hex code)
  border-radius: 10                   # Border corner radius in pixels
  border_width: 1                     # Border width in pixels

Shadow:
  # Shadow effect settings
  shadow_blur: 8                      # Shadow blur amount
  shadow_enable: false                # Enable/disable shadow
  shadow_offset_x: 2                  # Horizontal shadow offset
  shadow_offset_y: 2                  # Vertical shadow offset

ImageBadges:
  # Image badge settings
  codec_image_directory: "images/codec"   # Directory containing codec images
  enable_image_badges: true               # Use images instead of text when available
  fallback_to_text: true                  # Use text if image not found
  image_mapping:                          # Map codec names to image filenames
    # Examples (uncomment and modify as needed):
    # "ATMOS": "Atmos.png"
    # "DTS-HD MA": "DTS-HD.png"
    # "TRUEHD": "TrueHD.png"
  image_padding: 0                        # Padding around image badges
