General:
  # General badge settings
  badge_orientation: "vertical"       # Badge orientation (vertical, horizontal)
  badge_spacing: 15                   # Spacing between multiple badges
  general_badge_position: "bottom-left" # Position of the badge (top-left, top-right, bottom-left, bottom-right)
  general_badge_size: 500             # Base size of the badge in pixels
  general_edge_padding: 30            # Padding from the edge of the poster in pixels
  general_text_padding: 20            # Padding around text inside the badge
  max_badges_to_display: 4            # Maximum number of review badges to display
  use_dynamic_sizing: true            # Automatically adjust badge size based on content

Text:
  # Text appearance settings
  fallback_font: "DejaVuSans.ttf"     # Fallback font if primary font is not available
  font: ""                            # Primary font file to use (place in fonts directory)
  text-color: "#FFFFFF"               # Text color (hex code)
  text-size: 60                       # Text size relative to badge size

Background:
  # Badge background settings
  background-color: "#2C2C2C"         # Background color (hex code)
  background_opacity: 60              # Background opacity (0-100)

Border:
  # Badge border settings
  border-color: "#2C2C2C"             # Border color (hex code)
  border-radius: 10                   # Border corner radius in pixels
  border_width: 1                     # Border width in pixels

Shadow:
  # Shadow effect settings
  shadow_blur: 5                      # Shadow blur amount
  shadow_enable: false                # Enable/disable shadow
  shadow_offset_x: 2                  # Horizontal shadow offset
  shadow_offset_y: 2                  # Vertical shadow offset

ImageBadges:
  # Image badge settings
  codec_image_directory: "images/rating"  # Directory containing rating images
  enable_image_badges: true               # Use images instead of text when available
  fallback_to_text: true                  # Use text if image not found
  image_mapping:                          # Map review source names to image filenames
    # Examples (uncomment and modify as needed):
    # "IMDb": "IMDb.png"
    # "TMDb": "TMDb.png"
    # "RT-Crit-Fresh": "RT-Crit-Fresh.png"
  image_padding: 5                        # Padding around image badges
