api_keys:
  Jellyfin:
  - url: https://your-jellyfin-server.com
    api_key: YOUR_JELLYFIN_API_KEY
    user_id: YOUR_JELLYFIN_USER_ID
  OMDB:
  - api_key: YOUR_OMDB_API_KEY
    cache_expiration: 60
  TMDB:
  - api_key: YOUR_TMDB_API_KEY
    cache_expiration: 60
    language: en
    region: US
  aniDB:
  - username: YOUR_ANIDB_USERNAME
    password: YOUR_ANIDB_PASSWORD
    version: 5
    client_name: YOUR_CLIENT_NAME
    language: en
    cache_expiration: 60

tv_series:
  show_dominant_badges: true
  max_episodes_to_analyze: 5
  episode_timeout: 25

metadata_tagging:
  enabled: true
  tag_name: "aphrodite-overlay"
  tag_on_success_only: true

scheduler:
  enabled: true
  timezone: "America/Toronto"
  max_concurrent_jobs: 1
  job_history_limit: 50
