services:
  aphrodite:
    image: ghcr.io/jackkerouac/aphrodite:latest
    container_name: aphrodite
    ports:
      - "2125:5000"
    volumes:
      # Configuration files (auto-created if missing, fully customizable)
      - ./config:/app/config:rw
      
      # Persistent storage for posters and database
      - ./posters:/app/posters:rw
      - ./data:/app/data:rw
      
    environment:
      - TZ=UTC
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      
    restart: unless-stopped
