version: '3.8'

services:
  aphrodite:
    build:
      context: .
      dockerfile: Dockerfile.improved
    image: aphrodite:latest
    container_name: aphrodite-app
    hostname: aphrodite
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    volumes:
      # Data volume for persistence
      - aphrodite-data:/app/data
      
      # Poster storage
      - ./posters:/app/posters
      
      # Uncomment these for direct config file editing (optional)
      #- ./settings.yaml:/app/settings.yaml
      #- ./badge_settings_audio.yml:/app/badge_settings_audio.yml
      #- ./badge_settings_resolution.yml:/app/badge_settings_resolution.yml
      #- ./badge_settings_review.yml:/app/badge_settings_review.yml
    environment:
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent to Docker logs immediately
    networks:
      - aphrodite-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  aphrodite-data:
    driver: local

networks:
  aphrodite-net:
    driver: bridge
