api_keys:
  Jellyfin:
  - url: https://jellyfin.okaymedia.ca
    api_key: 6c921b79ca694f04b86c6e15a104e469
    user_id: 34b672a45581450dbb14bb6a0a2ae85b
  OMDB:
  - api_key: ''
    cache_expiration: 60
  TMDB:
  - api_key: ''
    cache_expiration: 60
    language: en
    region: null
  aniDB:
  - username: ''
  - password: ''
    version: 5
    client_name: ''
    language: en
    cache_expiration: 60
