api_keys:
  Jellyfin:
  - url: https://jellyfin.okaymedia.ca
    api_key: 6c921b79ca694f04b86c6e15a104e469
    user_id: 34b672a45581450dbb14bb6a0a2ae85b
  OMDB:
  - api_key: 4b8ba0e1
    cache_expiration: 60
  TMDB:
  - api_key: 0b2dc1bbbed569c9f97b2c54c7d167d2
    cache_expiration: 60
    language: en
    region: CA
  aniDB:
  - username: jackkerouac4657
  - password: Paradise4657
    version: 5
    client_name: kometamoore
    language: en
    cache_expiration: 60
