api_keys:
  Jellyfin:
    - url: "https://jellyfin.example.com"
      api_key: "your-api-key-here"
      user_id: "your-user-id-here"
  OMDB:
    - api_key: ""
  TMDB:
    - api_key: ""
  aniDB:
    - username: ""
      client: 1
      language: "en"
      cache_expiration: 60
