name: Build Docker Image and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check for pre-built frontend
      run: |
        if [ ! -d "frontend/.next" ]; then
          echo "ERROR: Frontend not pre-built!"
          echo "This prevents Tailwind v4 compilation issues"
          exit 1
        fi
        echo "Using pre-built frontend"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest
          
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/amd64

    - name: Update docker-compose.yml for release
      run: |
        # Update the image reference to use the actual repository
        sed -i 's|ghcr.io/your-username/aphrodite:latest|ghcr.io/${{ github.repository }}:latest|g' docker-compose.yml
        
    - name: Upload deployment files to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: docker-compose.yml
        asset_name: docker-compose.yml
        asset_content_type: text/yaml

    - name: Upload environment template to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .env.example
        asset_name: .env.example
        asset_content_type: text/plain
